project:
  type: website
execute:
  freeze: false
website:
  title: "E155 Portfolio"
  navbar:
    background: "primary"
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Labs
        menu:
          - text: lab 1 FPGA and MCU Setup and Testing
            href: labs/lab1/lab.qmd
          - text: lab 2 - Multiplexed 7 Segment Display
            href: labs/lab2/lab.qmd
          - text: lab 3 - Keypad Scanner
            href: labs/lab3/lab.qmd
          - text: lab 4 - Digital Audio
            href: labs/lab4/lab.qmd
          - text: lab 5 - Interrupts
            href: labs/lab5/lab.qmd
          - text: lab 6 - The Internet of Things and SPI
            href: labs/lab6/lab.qmd
          - text: lab 7 - The Advanced Encryption Standard (AES)
            href: labs/lab7/lab.qmd
      - text: resources
        href: resources.qmd
      - text: Blog
        href: blog.qmd
    tools:
      - icon: github
        text: Github
        href: https://github.com/Sorin-Jayaweera?tab=repositories

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true